version: '3.8'
services:
  homeserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6167:6167"
    volumes:
      - ./data:/var/lib/conduwuit
    environment:
      - CONDUWUIT_SERVER_NAME=localhost
      - CONDUWUIT_DATABASE_PATH=/var/lib/conduwuit/conduwuit.db
      - CONDUWUIT_PORT=6167
      - CONDUWUIT_ALLOW_ENCRYPTION=true

volumes:
  db:
