version: '3.8'
services:
  homeserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - pqchat_data:/var/lib/pqchat
    ports:
      - "6167:6167"
    environment:
      - RUST_LOG=info
    restart: unless-stopped

volumes:
  pqchat_data:
