version: '3.8'
services:
  homeserver:
    image: mnylif/pqchat:latest
    container_name: pqchat
    restart: unless-stopped
    ports:
      - "6167:6167"
    volumes:
      - ./data:/var/lib/pqchat
      - ./pqchat.toml:/var/lib/pqchat/pqchat.toml:ro
    environment:
      - RUST_LOG=info
