[package]
name = "conduwuit-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
pqcrypto-kyber = "0.7.8"
pqcrypto-dilithium = "0.5.0"
pqcrypto-traits = "0.3.5"
ruma = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
